import { slides } from './src/slides';
import { cp, mkdir, writeFile } from 'node:fs/promises';
await mkdir('dist', { recursive: true });
await cp('public', 'dist', { recursive: true });
const result = await Bun.build({ entrypoints: ['src/main.ts'], outdir: 'dist', target: 'browser', minify: true });
if (!result.success) throw new Error(result.logs.join('\n'));
await cp('src/style.css', 'dist/style.css');
const notes = slides.map(({ title, timing, script, source }) => ({ title, timing, script, source }));
await writeFile('dist/notes.json', JSON.stringify(notes));
await writeFile('speaker-notes.md', '# Trakr technical presentation\n\nSix technical slides (~3½ minutes), a three-minute demo, and one Q&A appendix. Generated from src/slides.ts.\n\n' + notes.map((n,i) => `## ${i+1}. ${n.title}\n\n**${n.timing}**\n\n${n.script}\n\nSource: ${n.source}\n`).join('\n'));
console.log(`Built presentation and ${notes.length} speaker notes.`);
