// Run in the loaded presentation with gstack browse eval.
return (async () => {
  const results = [];
  const check = (condition, message) => { if (!condition) throw new Error(message); results.push(message); };
  const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
  const go = index => document.querySelector(`[data-goto="${index}"]`).click();
  await document.fonts.ready;
  go(0);
  check(document.querySelector('#previous').disabled, 'Previous disabled on first slide');
  document.body.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }));
  check(location.hash === '#2', 'Arrow key advances and updates the link');
  check(document.querySelectorAll('.slide:not([hidden])').length === 1, 'Exactly one slide is exposed');
  document.querySelector('#overview').click();
  check(document.querySelector('#slide-picker').open, 'Slide overview opens');
  go(3);
  check(!document.querySelector('#slide-picker').open && location.hash === '#4', 'Overview jumps and closes');
  document.querySelector('#play-flow').click();
  await wait(2450);
  check(document.querySelector('#receipt-state').textContent === 'CONFIRMED', 'Checkout animation reaches receipt');
  document.querySelector('#play-flow').click();
  check(document.querySelector('#receipt-state').textContent === 'STAGED', 'Replay starts from staged state');
  go(4);
  await wait(2450);
  check(document.querySelector('#receipt-state').textContent === 'STAGED', 'Leaving the slide cancels animation timers');
  document.querySelector('#notes').click();
  check(document.querySelector('#speaker').open && document.querySelector('#speaker-content').textContent.includes('NFC'), 'Relevant presenter notes load');
  document.querySelector('#speaker [data-close]').click();
  go(9);
  document.querySelector('#timer-toggle').click();
  await wait(1150);
  document.querySelector('#timer-toggle').click();
  check(document.querySelector('#timer').textContent !== '3:00', 'Demo timer counts down');
  const paused = document.querySelector('#timer').textContent;
  await wait(1100);
  check(document.querySelector('#timer').textContent === paused, 'Demo timer pauses');
  document.querySelector('#timer-reset').click();
  check(document.querySelector('#timer').textContent === '3:00', 'Demo timer resets');
  go(17);
  check(document.querySelector('#next').disabled, 'Next disabled on final slide');
  go(0);
  return { passed: results.length, results };
})();
