// Run in the loaded presentation with gstack browse eval.
return (async () => {
  const results = [];
  const check = (condition, message) => { if (!condition) throw new Error(message); results.push(message); };
  const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
  const go = index => document.querySelector(`[data-goto="${index}"]`).click();
  await document.fonts.ready;
  check(document.querySelectorAll('.slide').length === 8, 'Shortened deck has eight slides');
  go(0);
  check(document.querySelector('#previous').disabled, 'Previous disabled on first slide');
  document.body.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }));
  check(location.hash === '#2', 'Arrow key advances and updates the link');
  check(document.querySelectorAll('.slide:not([hidden])').length === 1, 'Exactly one slide is exposed');
  document.querySelector('#overview').click();
  check(document.querySelector('#slide-picker').open, 'Slide overview opens');
  go(2);
  check(!document.querySelector('#slide-picker').open && location.hash === '#3', 'Overview jumps and closes');
  document.querySelector('#play-flow').click();
  await wait(2450);
  check(document.querySelector('#trace-receipt').classList.contains('traced'), 'Flowchart trace reaches committed receipt');
  document.querySelector('#play-flow').click();
  check(!document.querySelector('#trace-receipt').classList.contains('traced'), 'Replay clears the completed path');
  go(4);
  await wait(2450);
  check(!document.querySelector('#trace-receipt').classList.contains('traced'), 'Leaving the slide cancels animation timers');
  document.querySelector('#notes').click();
  check(document.querySelector('#speaker').open && document.querySelector('#speaker-content').textContent.includes('one plus n plus k'), 'Relevant presenter notes load');
  document.querySelector('#speaker [data-close]').click();
  const itemInput = document.querySelector('#item-count');
  const issueInput = document.querySelector('#issue-count');
  check(document.querySelector('#write-total').textContent === '8', 'Five items and two issues produce eight writes');
  itemInput.value = '20'; itemInput.dispatchEvent(new Event('input', { bubbles: true }));
  issueInput.value = '20'; issueInput.dispatchEvent(new Event('input', { bubbles: true }));
  check(document.querySelector('#write-total').textContent === '41', 'Twenty items and twenty issues produce 41 writes');
  itemInput.value = '1'; itemInput.dispatchEvent(new Event('input', { bubbles: true }));
  check(issueInput.value === '1' && document.querySelector('#write-total').textContent === '3', 'Issue count clamps when item count decreases');
  issueInput.value = '0'; issueInput.dispatchEvent(new Event('input', { bubbles: true }));
  check(document.querySelector('#write-total').textContent === '2', 'One item without issues produces two writes');
  itemInput.focus();
  itemInput.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }));
  check(location.hash === '#5', 'Slider keyboard input does not change slides');
  itemInput.value = '5'; itemInput.dispatchEvent(new Event('input', { bubbles: true }));
  issueInput.value = '2'; issueInput.dispatchEvent(new Event('input', { bubbles: true }));
  go(6);
  document.querySelector('#timer-toggle').click();
  await wait(1150);
  document.querySelector('#timer-toggle').click();
  check(document.querySelector('#timer').textContent !== '3:00', 'Demo timer counts down');
  const paused = document.querySelector('#timer').textContent;
  await wait(1100);
  check(document.querySelector('#timer').textContent === paused, 'Demo timer pauses');
  document.querySelector('#timer-reset').click();
  check(document.querySelector('#timer').textContent === '3:00', 'Demo timer resets');
  go(7);
  check(document.querySelector('#next').disabled, 'Next disabled on final slide');
  go(0);
  return { passed: results.length, results };
})();
