export {};
type Slide = { title: string; section: string; html: string };
const tag = `<svg viewBox="0 0 160 160" class="tag-art" fill="none" aria-hidden="true"><path d="M34 33h59l39 40-60 60-38-39Z" stroke="currentColor" stroke-width="2"/><circle cx="58" cy="57" r="6" stroke="currentColor" stroke-width="2"/><path class="signal s1" d="M84 58a21 21 0 0 1 18 18"/><path class="signal s2" d="M85 47a32 32 0 0 1 28 28"/><path class="signal s3" d="M87 36a43 43 0 0 1 37 37"/></svg>`;
const camera = `<svg viewBox="0 0 240 160" fill="none" aria-hidden="true"><path d="M38 49h38l12-18h61l13 18h39v91H38Z" stroke="currentColor" stroke-width="2"/><circle cx="123" cy="92" r="31" stroke="currentColor" stroke-width="2"/><circle cx="123" cy="92" r="22" stroke="currentColor"/><path d="M52 39h20M174 64h13" stroke="currentColor" stroke-width="3"/></svg>`;
const eyebrow = (s:string) => `<p class="eyebrow">${s}</p>`;
const row = (a:string,b:string) => `<div class="detail-row"><h3>${a}</h3><p>${b}</p></div>`;
const slides: Slide[] = [
{title:'Equipment, accounted for.',section:'The idea',html:`<div class="hero-copy">${eyebrow('NFC EQUIPMENT CHECKOUT · iOS + ANDROID')}<h1>Equipment,<br><span class="muted">accounted for.</span></h1><p class="lead">A tap to borrow. A record to return to.</p><p class="quiet hero-credit">Built for school equipment rooms.</p></div><div class="hero-object reveal"><div class="asset-label"><span>CAMERA / 014</span><span class="status-dot"></span></div><div class="camera-drawing">${camera}</div><div class="asset-tag">${tag}<span>Tap to identify</span></div><div class="asset-bottom"><span>School equipment</span><span>trakr</span></div></div><p class="slide-foot">5-minute presentation <span> / </span> 3-minute live demo</p>`},
{title:'The equipment comes back. The context often doesn’t.',section:'The problem',html:`${eyebrow('THE PROBLEM')}<h2>The equipment comes back.<br><span class="muted">The context often doesn’t.</span></h2><div class="problem-layout"><div class="questions"><p class="reveal">Who took the camera?</p><p class="reveal">Was the strap already loose?</p><p class="reveal">Has anyone checked it back in?</p></div><div class="fragment"><span class="mono quiet">A TYPICAL HANDOVER</span><div class="message">“I think someone returned it.”<span>In a chat somewhere</span></div><div class="paper-row"><span>Camera 014</span><span>Borrower —</span><span>Return —</span></div><p class="quiet">A name in a log is only part of the story.</p></div></div><p class="slide-foot">Problem hypothesis: scattered records create avoidable follow-up.</p>`},
{title:'One handover. Both sides covered.',section:'Who it helps',html:`${eyebrow('THE USE CASE')}<h2>One handover.<br><span class="muted">Both sides covered.</span></h2><div class="roles"><div class="role reveal"><span class="mono quiet">STUDENT</span><h3>Borrow with a record.</h3><p>Scan a camera and tripod.<br>Record their condition.<br>Keep a checkout receipt.</p></div><div class="handover-mark">${tag}</div><div class="role reveal"><span class="mono quiet">TEACHER</span><h3>Close the loop.</h3><p>See active claimants.<br>Confirm returned equipment.<br>Follow up on reported issues.</p></div></div><p class="slide-foot">Equipment leads get inventory and claim oversight through the ops dashboard.</p>`},
{title:'From tap to receipt.',section:'The workflow',html:`<div class="workflow-copy">${eyebrow('THE STUDENT JOURNEY')}<h2>From tap<br><span class="muted">to receipt.</span></h2><ol class="steps"><li class="selected" data-step="0"><span>01</span>Scan the equipment</li><li data-step="1"><span>02</span>Record the condition</li><li data-step="2"><span>03</span>Confirm the checkout</li></ol><button class="primary" id="play-flow">Play the handover <span>↗</span></button><p class="quiet small">Illustrative workflow, not a live app session.</p></div><div class="receipt reveal"><div class="receipt-top"><span>trakr</span><span class="mono quiet" id="receipt-state">STAGED</span></div><h3 id="receipt-title">Ready to borrow.</h3><div class="receipt-item">${camera}<div><strong>Camera 014</strong><span id="camera-condition">Condition to review</span></div><span class="item-check">✓</span></div><div class="receipt-item"><span class="tripod-icon">⋀</span><div><strong>Tripod 008</strong><span id="tripod-condition">Condition to review</span></div><span class="item-check">✓</span></div><div class="issue-note" id="issue-note">Condition note: loose camera strap.</div><div class="receipt-total"><span>2 items</span><strong id="receipt-result">Awaiting confirmation</strong></div><div class="receipt-stamp" id="receipt-stamp">✓ Checkout recorded</div></div><p class="slide-foot">The teacher confirms the return. An issue stays open until it is addressed.</p>`},
{title:'A physical tap. A shared record.',section:'Data flow',html:`${eyebrow('UNDER THE HOOD')}<h2>A physical tap.<br><span class="muted">A shared record.</span></h2><div class="identity-line"><span class="identity-dot"></span>Google sign-in <span class="quiet">supplies verified school identity</span></div><div class="data-flow"><div class="flow-node"><span class="mono">01 / IDENTIFY</span><h3>NFC tag</h3><p>Item identifier<br><code>tr:…</code></p></div><div class="wire"><i></i></div><div class="flow-node"><span class="mono">02 / PREPARE</span><h3>Native app</h3><p>Resolve equipment<br>Stage + validate</p></div><div class="wire"><i></i></div><div class="flow-node"><span class="mono">03 / AUTHORIZE</span><h3>Security Rules</h3><p>Role + ownership<br>Allowed changes</p></div><div class="wire"><i></i></div><div class="flow-node"><span class="mono">04 / COMMIT</span><h3>Firestore</h3><p>Batch + claims<br>Optional issues</p></div></div><div class="atomic"><span>↳</span><p><strong>All together, or not at all.</strong> Related checkout writes commit as one atomic batch.</p></div><p class="slide-foot">Teacher return → claim status updated. The ops dashboard uses a separate privileged Worker path.</p>`},
{title:'The details make it dependable.',section:'Engineering',html:`${eyebrow('ENGINEERING DECISIONS')}<h2>The details make<br><span class="muted">it dependable.</span></h2><div class="engineering">${row('Access is enforced.','Database rules check identity and ownership, beyond what the interface shows.')}${row('Offline is explicit.','Staged items remain. Confirmation waits for a connection.')}${row('History outlives the tag.','Tag replacement keeps the equipment identity and claim history.')}</div><p class="slide-foot">Repository coverage: store, UI and Firestore rules tests. Physical-device validation remains a pilot step.</p>`},
{title:'Prove it in one room.',section:'Validation',html:`${eyebrow('PROPOSED FOUR-WEEK PILOT')}<h2>Prove it<br><span class="muted">in one room.</span></h2><div class="pilot-layout"><div class="timeline"><div><span class="mono">WEEK 1</span><h3>Observe the baseline.</h3><p>Time handovers. Interview teachers. Enroll tags.</p></div><div><span class="mono">WEEKS 2–3</span><h3>Use it for real.</h3><p>Watch completion, failures and staff follow-up.</p></div><div><span class="mono">WEEK 4</span><h3>Compare. Then decide.</h3><p>Expand only if the workflow earns its place.</p></div></div><div class="targets"><p class="mono quiet">PROPOSED TARGETS, NOT RESULTS</p><div><strong>30<span>%</span></strong><p>lower median checkout time</p></div><div><strong>95<span>%</span></strong><p>complete handover records</p></div></div></div>`},
{title:'A school buys less chasing.',section:'Business case',html:`${eyebrow('BUSINESS HYPOTHESIS')}<h2>A school buys<br><span class="muted">less chasing.</span></h2><div class="business"><div class="commercial"><span class="mono quiet">PROPOSED MODEL</span><h3>Annual school subscription.</h3><p>Optional onboarding for inventory and tags.<br>Pricing follows measured value and buyer feedback.</p><div class="expansion"><span>One room</span><b>→</b><span>More departments</span><b>→</b><span>More schools</span></div></div><div class="next-proof"><span class="mono quiet">WHAT INVESTORS NEED NEXT</span><p>Repeat use.</p><p>Willingness to pay.</p><p>Support cost per school.</p></div></div><p class="slide-foot">No validated pricing or traction yet. Multi-school isolation and repeatable onboarding are future work.</p>`},
{title:'One room. One teacher. Four weeks.',section:'The ask',html:`${eyebrow('THE NEXT STEP')}<h2 class="ask-title">One room.<br>One teacher.<br><span class="muted">Four weeks.</span></h2><div class="ask-aside"><p>A small pilot.<br>A measurable answer.</p><p class="quiet">Time saved. Record quality.<br>A clear go / no-go decision.</p></div><p class="slide-foot">Now, let’s show the handover. <span class="accent">→</span></p>`},
{title:'Let’s borrow a camera.',section:'Live demo',html:`${eyebrow('THREE-MINUTE LIVE DEMO')}<h2>Let’s borrow<br><span class="muted">a camera.</span></h2><div class="demo-layout"><div class="demo-sequence">${row('Student checkout','Scan two items. Record a loose strap. Confirm and show the receipt.')}${row('Teacher return','Review active claims. Confirm the equipment is back.')}${row('Close the loop','Show the returned record and acknowledge the issue.')}</div><div class="demo-clock"><span class="mono quiet">DEMO TIMER</span><output id="timer">3:00</output><button id="timer-toggle" class="primary">Start timer</button><button id="timer-reset" class="text-button">Reset</button></div></div><p class="slide-foot">Use the native app for the live demo. A local simulation does not prove cross-device sync.</p>`},
];
const appendix: [string,string,string][] = [
['The record survives the tag.','Data model',`${row('Equipment → tags','A stable equipment ID links the current tag and serial number.')}${row('Checkout batch → claims','Each claim links the borrower, equipment, condition and tag used.')}${row('Claims → issues / return batch','Issues track resolution separately. A teacher return closes active claims.')}`],
['Two paths. Two trust boundaries.','Security',`${row('Mobile → Security Rules → Firestore','Verified school identity, role, ownership, schemas and state transitions.')}${row('Staff browser → Worker → Firestore','The privileged service-account path needs its own authorization and validation. Ops mutations are audited.')}${row('Before a broader launch','Isolate demo data, disable demo access, validate credentials and redesign tenant boundaries.')}`],
['What the MVP doesn’t claim.','Limits',`${row('No guaranteed background alerts','Overdue status is calculated in-app. Confirmation requires connectivity.')}${row('No exclusive reservations','Multiple active claims are allowed. Concurrency needs device and pilot validation.')}${row('No theft prevention','NFC identifies an item. It does not locate it or make a tag uncloneable.')}`],
['Show the work behind the pitch.','Assessment',`${row('Problem & design','Concrete user scenario, user roles and an explainable data flow.')}${row('Implementation & quality','A checkout-to-return demonstration, repository test coverage and honest device-validation gaps.')}${row('Critical evaluation','Alternatives, explicit constraints, baseline measurements and a proposed pilot decision rule.')}`],
['NFC has to earn its place.','Alternatives',`${row('Paper / spreadsheets','Familiar, low setup burden. Completeness depends on process discipline.')}${row('QR / NFC forms','Credible lightweight alternatives. Compare reliability, device coverage and task completion.')}${row('Trakr','Connect checkout, condition, receipt and teacher-confirmed return. Differentiate through the completed workflow.')}`],
['Agree on success before starting.','Pilot scorecard',`${row('Speed & completeness','Proposed: ≥30% lower median checkout time and ≥95% complete eligible handover records.')}${row('Reliability & access','Track failed commits and recovery. Require zero unauthorized reads in the security test set.')}${row('Adoption','Record sample sizes, compare similar tasks and measure staff follow-up time and continued use.')}`],
['Value first. Pricing second.','Economics',`${row('Illustrative time value','2 staff hours × S$30 × 40 weeks = S$2,400 per school year. An assumption, not measured savings or revenue.')}${row('The costs still count','Subtract tags, onboarding, hosting, support and acquisition. Validate budget ownership and willingness to pay.')}${row('Before commercial expansion','Validate retention, school procurement, tenant isolation and commercial rights under the current repository license.')}`],
['Implementation ≠ field validation.','Evidence',`${row('Product & architecture','README.md, Domain.swift, FirebaseGateway.swift and NFCService.swift.')}${row('Security & verification','firestore.rules, dashboard documentation and docs/mvp-verification.md. No new application test pass is claimed.')}${row('Evidence to collect next','Teacher interviews, baseline timings, physical-device results, pilot adoption and buyer feedback.')}`],
];
appendix.forEach(([title,section,html])=>slides.push({title,section,html:`${eyebrow('APPENDIX / '+section.toUpperCase())}<h2 class="appendix-title">${title}</h2><div class="appendix-rows">${html}</div>`}));
const $ = <T extends HTMLElement = HTMLElement>(selector:string) => {const el=document.querySelector<T>(selector); if(!el) throw new Error(`Missing ${selector}`); return el;};
$('#deck').innerHTML=slides.map((s,i)=>`<section class="slide slide-${i+1}" id="slide-${i+1}" aria-label="${s.section}" ${i?'hidden':''}>${s.html}</section>`).join('');
let index=0; let flowTimers: ReturnType<typeof setTimeout>[]=[]; let timerInterval: ReturnType<typeof setInterval>|undefined; let remaining=180; let deadline=0;
const picker=$<HTMLDialogElement>('#slide-picker'); const speaker=$<HTMLDialogElement>('#speaker');
type Note={title:string;timing:string;script:string;source:string}; let notes:Note[]=[];
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
fetch('/notes.json').then(r=>{if(!r.ok)throw new Error('Notes unavailable');return r.json()}).then((n:Note[])=>{notes=n;updateNotes()}).catch(()=>{$('#speaker-content').textContent='Speaker notes could not load. Please refresh to retry.'});
function updateNotes(){const n=notes[index];if(n)$('#speaker-content').innerHTML=`<p class="mono accent">${escape(n.timing)}</p><h3>${escape(slides[index].title)}</h3><p>${escape(n.script)}</p><p class="note-source">${escape(n.source)}</p>`;}
function stopFlow(){flowTimers.forEach(clearTimeout);flowTimers=[];}
function setFlow(step:number){document.querySelectorAll('[data-step]').forEach((el,i)=>el.classList.toggle('selected',i===step));$('#receipt-state').textContent=['STAGED','REVIEWED','CONFIRMED'][step];$('#receipt-title').textContent=step===2?'You’re checked out.':'Ready to borrow.';$('#camera-condition').textContent=step?'Loose strap reported':'Condition to review';$('#tripod-condition').textContent=step?'No issues':'Condition to review';$('#issue-note').classList.toggle('shown',step>0);$('#receipt-stamp').classList.toggle('shown',step===2);$('#receipt-result').textContent=step===2?'Receipt saved':'Awaiting confirmation';$('.receipt').classList.toggle('confirmed',step===2);}
function go(next:number){index=Math.max(0,Math.min(slides.length-1,next));stopFlow();document.querySelectorAll<HTMLElement>('.slide').forEach((el,i)=>{el.hidden=i!==index;el.classList.toggle('active',i===index);el.inert=i!==index;});if(index===3)setFlow(0);$('#counter').textContent=`${String(index+1).padStart(2,'0')} / ${slides.length}`;$('#section-name').textContent=(index>=10?'Appendix · ':'')+slides[index].section;$<HTMLButtonElement>('#previous').disabled=index===0;$<HTMLButtonElement>('#next').disabled=index===slides.length-1;$('#progress-fill').style.width=`${(index+1)/slides.length*100}%`;history.replaceState(null,'',`#${index+1}`);document.title=`Trakr · ${slides[index].title}`;window.scrollTo({top:0,behavior:'instant'});updateNotes();}
$('#next').onclick=()=>go(index+1);$('#previous').onclick=()=>go(index-1);
$('#play-flow').onclick=()=>{stopFlow();setFlow(0);flowTimers.push(setTimeout(()=>setFlow(1),1000),setTimeout(()=>setFlow(2),2300));};
$('#overview').onclick=()=>picker.showModal();$('#notes').onclick=()=>speaker.showModal();
$('#slide-list').innerHTML=slides.map((s,i)=>`<button data-goto="${i}"><span class="mono">${String(i+1).padStart(2,'0')}</span><span>${escape(s.title)}</span>${i>=10?'<small>Q&A</small>':''}</button>`).join('');
$('#slide-list').onclick=e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-goto]');if(b){go(Number(b.dataset.goto));picker.close();}};
document.querySelectorAll<HTMLButtonElement>('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog')?.close());
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('#announcement').textContent='Fullscreen is unavailable in this browser. Use the browser presentation controls.';}}
$('#fullscreen').onclick=fullscreen;
document.addEventListener('fullscreenchange',()=>$('#fullscreen').setAttribute('aria-label',document.fullscreenElement?'Exit fullscreen':'Enter fullscreen'));
function renderTimer(){$('#timer').textContent=`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`;}
function pauseTimer(){clearInterval(timerInterval);timerInterval=undefined;$('#timer-toggle').textContent=remaining===0?'Restart timer':'Resume timer';}
$('#timer-toggle').onclick=()=>{if(timerInterval){remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));pauseTimer();renderTimer();return;}if(remaining===0)remaining=180;deadline=Date.now()+remaining*1000;$('#timer-toggle').textContent='Pause timer';timerInterval=setInterval(()=>{remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));renderTimer();if(remaining===0){pauseTimer();$('#announcement').textContent='Three-minute demo complete.';}},250);};
$('#timer-reset').onclick=()=>{pauseTimer();remaining=180;renderTimer();$('#timer-toggle').textContent='Start timer';};
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||picker.open||speaker.open)return;const target=e.target as HTMLElement;if(target.closest('button,a,input,textarea,select')&&(e.key===' '||e.key==='Enter'))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();go(index+1);}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(index-1);}else if(e.key==='Home')go(0);else if(e.key==='End')go(slides.length-1);else if(e.key.toLowerCase()==='f')void fullscreen();else if(e.key.toLowerCase()==='n')speaker.showModal();else if(e.key.toLowerCase()==='o')picker.showModal();});
let touchX=0,touchY=0;$('#deck').addEventListener('touchstart',e=>{touchX=e.changedTouches[0].clientX;touchY=e.changedTouches[0].clientY;},{passive:true});$('#deck').addEventListener('touchend',e=>{if((e.target as HTMLElement).closest('button'))return;const dx=e.changedTouches[0].clientX-touchX,dy=e.changedTouches[0].clientY-touchY;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.5)go(index+(dx<0?1:-1));},{passive:true});
function fromHash(){const n=Number(location.hash.slice(1));go(Number.isFinite(n)&&n>=1?n-1:0);}window.addEventListener('hashchange',fromHash);fromHash();
