export type Slide = {
  title: string;
  section: string;
  layout?: string;
  html: string;
  timing: string;
  script: string;
  source: string;
};
const eyebrow = (text: string) => `<p class="eyebrow">${text}</p>`;
const foot = (text: string) => `<p class="slide-foot">${text}</p>`;
const row = (title: string, body: string) => `<div class="detail-row"><h3>${title}</h3><p>${body}</p></div>`;

export const slides: Slide[] = [
  {
    title: 'Know who has it. Know it came back.', section: 'The idea', layout: 'balanced-intro',
    html: `${eyebrow('TRAKR / SCHOOL EQUIPMENT CHECKOUT')}<h1>Know who has it.<br><span class="muted">Know it came back.</span></h1><p class="lead">Connect borrowing, condition and return<br>in one shared record.</p><div class="intro-caption"><span class="mono">THE STARTING POINT</span><p>A camera leaves the equipment room.<br>The teacher should not have to piece together what happened next.</p></div>${foot('6 short slides · ~3½ minutes · then a 3-minute live demo')}`,
    timing: '0:00–0:20 · 20 seconds',
    script: 'A camera leaves the school equipment room. Later, a teacher needs to know who borrowed it, what condition it was in, and whether it came back. Trakr connects those moments in one record, using an NFC tap and a school account. The aim is clearer handovers and less follow-up work.',
    source: 'README.md; problem framing is a hypothesis to validate with teachers.',
  },
  {
    title: 'The problem is the missing context.', section: 'The problem',
    html: `${eyebrow('THE PROBLEM STATEMENT')}<h2>The item is shared.<br><span class="muted">The context gets scattered.</span></h2><div class="problem-statement"><p>When the log, condition report and return are separate, staff have to reconstruct the handover.</p></div><div class="problem-columns"><div><span class="mono quiet">BORROWER</span><h3>“Who took it?”</h3><p>Missing or scattered details make follow-up harder.</p></div><div><span class="mono quiet">CONDITION</span><h3>“Was it already broken?”</h3><p>Without a handover record, responsibility is unclear.</p></div><div><span class="mono quiet">RETURN</span><h3>“Is it actually back?”</h3><p>A message or a physical drop-off can leave the log unfinished.</p></div></div>${foot('Problem hypothesis: fragmented records create avoidable chasing, uncertainty and disputes.')}`,
    timing: '0:20–1:00 · 40 seconds',
    script: 'A borrowing log can record a name, but the rest of the story may sit somewhere else: a message about damage, a verbal reminder, or an item dropped back on a shelf. The teacher then has to reconstruct who had it, whether the fault was already there and whether the return was checked. Students also benefit from a clear record of the condition they reported. We are not claiming every school has this problem at the same scale. The pilot needs to establish how often these gaps occur and how much staff time they consume.',
    source: 'Illustrative school workflow; no interview findings or measured savings are claimed.',
  },
  {
    title: 'Make the handover the moment of record.', section: 'The use case',
    html: `${eyebrow('ONE EXAMPLE / A CAMERA AND A TRIPOD')}<h2>A quick checkout.<br><span class="muted">A clear return.</span></h2><div class="user-pair"><div><span class="mono quiet">STUDENT</span><h3>Borrow with a receipt.</h3><p>Tap both equipment tags.<br>Report the camera’s loose strap.<br>Confirm and keep the checkout record.</p></div><div><span class="mono quiet">TEACHER</span><h3>See what needs attention.</h3><p>Review who claimed the items.<br>Confirm they have been returned.<br>Follow up on the reported strap issue.</p></div></div><div class="takeaway"><span class="accent">✓</span><p>The condition is recorded before checkout. A return does not automatically close the issue.</p></div>${foot('Implemented in native iOS and Android workflows; NFC and school sign-in still need validation in the intended environment.')}`,
    timing: '1:00–1:35 · 35 seconds',
    script: 'Here is the use case we will demonstrate. A student borrows a camera and tripod. They scan both tags, see the staged items, report the camera’s loose strap and confirm checkout. The receipt gives them a record of what they took and the condition they reported. When the equipment comes back, a teacher reviews the active claims and confirms the return. The loose strap remains a separate issue to follow up. That distinction matters: returned equipment is not necessarily repaired equipment.',
    source: 'README.md; Trakr/Features/Checkout/CheckoutView.swift; Trakr/Features/Returns/ReturnView.swift; Trakr/Models/Domain.swift',
  },
  {
    title: 'One tap connects the whole handover.', section: 'Overall data flow',
    html: `${eyebrow('HOW IT WORKS / OVERALL DATA FLOW')}<h2>A physical item.<span class="muted"> A shared record.</span></h2><div class="flow-toolbar"><p class="diagram-intro">The school account identifies the person. The NFC tag identifies the equipment.</p><button class="text-button" id="play-flow">Trace the handover ↗</button></div><div class="identity-caption"><span class="accent">●</span> School sign-in <span class="quiet">gives students and teachers the appropriate access.</span></div><svg class="technical-diagram overall-flow" viewBox="0 0 1120 250" role="img" aria-label="Equipment tag is scanned by the student app. The app saves the borrower, items and condition to shared Firebase records after access checks. Teachers read the record and update it when confirming a return or following up on an issue."><defs><marker id="handover-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M1 1L7 4L1 7" fill="none" stroke="#91b8fb" stroke-width="1.2"/></marker></defs><g class="diagram-node" id="trace-scan"><rect x="15" y="45" width="210" height="95" rx="8"/><text x="35" y="80" class="node-title">Equipment tag</text><text x="35" y="106" class="node-sub">Identifies the item</text></g><path class="diagram-line" d="M225 93H305" marker-end="url(#handover-arrow)"/><text x="251" y="77" class="edge-label">tap</text><g class="diagram-node" id="trace-stage"><rect x="305" y="45" width="210" height="95" rx="8"/><text x="325" y="80" class="node-title">Student app</text><text x="325" y="106" class="node-sub">Items + condition</text></g><path class="diagram-line" d="M515 93H595" marker-end="url(#handover-arrow)"/><text x="535" y="77" class="edge-label">save</text><g class="diagram-node" id="trace-commit"><rect x="595" y="45" width="230" height="95" rx="8"/><text x="615" y="80" class="node-title">Shared records</text><text x="615" y="106" class="node-sub">Firebase + access checks</text></g><path class="diagram-line" d="M825 93H895" marker-end="url(#handover-arrow)"/><text x="840" y="77" class="edge-label">view</text><g class="diagram-node" id="trace-receipt"><rect x="895" y="45" width="210" height="95" rx="8"/><text x="915" y="80" class="node-title">Teacher view</text><text x="915" y="106" class="node-sub">Return + issue follow-up</text></g><path class="diagram-line" d="M1000 140V212H710V140" marker-end="url(#handover-arrow)"/><text x="756" y="195" class="edge-label">Update the same record</text></svg><p class="trace-caption mono" id="trace-status" aria-live="polite">READY / trace the handover</p>${foot('Students see their own claims. Teachers manage returns and issues. Related checkout records are saved together.')}`,
    timing: '1:35–2:15 · 40 seconds',
    script: 'This is the overall data flow. The school account tells Trakr who the person is, while the tag identifies the physical equipment. The student app brings the selected items and their condition into a checkout. After access checks, Firebase stores the related records together. The teacher can then view active claims, confirm a return and follow up on issues, updating the same shared record. Students see their own claims rather than another student’s borrowing history. This is the technical foundation behind the simple handover: identity, an item and a record that both sides can act on.',
    source: 'Trakr/NFC/NFCService.swift; Trakr/Services/FirebaseGateway.swift; firebase/firestore.rules; dashboard/README.md',
  },
  {
    title: 'Less chasing. Clearer accountability.', section: 'Why it matters',
    html: `${eyebrow('THE VALUE / WHAT CHANGES')}<h2>Less chasing.<br><span class="muted">Clearer accountability.</span></h2><div class="value-comparison"><div class="value-row value-head"><span>THE QUESTION</span><span>WITH A CONNECTED HANDOVER</span></div><div class="value-row"><h3>Who should I ask?</h3><p>The teacher can see the active claimant.</p></div><div class="value-row"><h3>What was reported?</h3><p>The condition note stays linked to the checkout.</p></div><div class="value-row"><h3>Has it been returned?</h3><p>A teacher-confirmed return closes the active claims.</p></div></div><div class="scope-note"><span class="mono">BUILT FOR ACCOUNTABILITY</span><p>Internet is required to confirm. Trakr records handovers; it does not locate equipment or prevent theft.</p></div>${foot('The workflow is implemented. Time savings, adoption and reliability still need to be measured in a school pilot.')}`,
    timing: '2:15–2:55 · 40 seconds',
    script: 'The value is that each question has a record to turn to. A teacher can see the active claimant, inspect the condition reported at checkout and confirm when the equipment comes back. Students get a clearer account of their own handover. A spreadsheet or form may be enough for some schools; Trakr needs to earn its place by making the complete workflow easier to finish. It requires internet to confirm and it is not a location tracker or an anti-theft system. The expected benefit is less chasing and ambiguity, but that benefit still needs to be measured.',
    source: 'README.md; docs/production-integration.md; docs/mvp-verification.md. Benefits are hypotheses, not measured outcomes.',
  },
  {
    title: 'Start with one equipment room.', section: 'Pilot & business case',
    html: `${eyebrow('NEXT STEP / A MEASURED PILOT')}<h2>One room.<span class="muted"> Four weeks.</span></h2><div class="pilot-pair"><div><span class="mono quiet">PROVE THE BENEFIT</span><h3>A teacher-led pilot.</h3><p>Observe the current handover.<br>Use Trakr for real borrowing.<br>Compare time, record completeness and follow-up.</p></div><div><span class="mono quiet">TEST THE BUSINESS</span><h3>A school subscription.</h3><p>Proposed buyer: the school or department.<br>Validate willingness to pay and support effort.<br>Expand only after repeat use.</p></div></div><p class="pilot-ask">The ask: one equipment room and one teacher sponsor.</p>${foot('Pilot and subscription are proposals. No measured savings, paying customers or validated pricing are claimed.')}`,
    timing: '2:55–3:30 · 35 seconds',
    script: 'The next step is one equipment room, one teacher sponsor and four weeks. Observe the current process first, then compare checkout time, completeness of records and staff follow-up while using Trakr. The business hypothesis is a school subscription, with onboarding support for inventory and tags. Before expanding, we need evidence that staff continue to use it, a buyer is willing to pay and support effort is manageable. Our ask is a focused pilot that answers those questions. Now we will show the borrowing and return workflow in three minutes.',
    source: 'Proposed pilot and commercial model; no customer traction, price or market-size claim.',
  },
  {
    title: 'Let’s borrow a camera.', section: 'Live demo', layout: 'balanced-demo',
    html: `${eyebrow('THREE-MINUTE LIVE DEMO')}<h2>Let’s borrow <span class="muted">a camera.</span></h2><div class="demo-layout"><div class="demo-sequence">${row('Student checkout','Scan the camera and tripod.<br>Report the loose strap. Confirm and show the receipt.')}${row('Teacher return','Review who borrowed the items.<br>Confirm that the equipment is back.')}${row('Issue follow-up','Show the returned record.<br>Acknowledge the strap issue separately.')}</div><div class="demo-clock"><span class="mono quiet">DEMO TIMER</span><output id="timer">3:00</output><button id="timer-toggle" class="primary">Start timer</button><button id="timer-reset" class="text-button">Reset</button></div></div>${foot('Demonstrate the native app. Clearly identify any local simulation or fallback recording.')}`,
    timing: '3:30–6:30 · 3-minute demo',
    script: '0:00–0:20: Introduce the prepared student account and two enrolled test items. 0:20–1:00: Scan the camera and tripod and show the staging list. 1:00–1:35: Report the loose camera strap, acknowledge the tripod condition, confirm and show the receipt. 1:35–2:20: Switch to the teacher session, review active claimants and confirm return. 2:20–2:45: Show the returned record and acknowledge the issue, explaining that returned does not mean repaired. 2:45–3:00: Close with the pilot ask. Use a dedicated test environment; identify simulated NFC or local data clearly. Independent local sessions do not prove cross-device sync.',
    source: 'docs/presentation/demo-runbook.md; README.md',
  },
];
