export type Slide = {
  title: string;
  section: string;
  layout?: string;
  appendix?: boolean;
  html: string;
  timing: string;
  script: string;
  source: string;
};
const eyebrow = (text: string) => `<p class="eyebrow">${text}</p>`;
const foot = (text: string) => `<p class="slide-foot">${text}</p>`;
const svg = (label: string, content: string, height = 290) => `<svg class="technical-diagram" viewBox="0 0 1120 ${height}" role="img" aria-label="${label}"><defs><marker id="arrow-${height}" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M1 1L7 4L1 7" fill="none" stroke="#91b8fb" stroke-width="1.2"/></marker></defs>${content}</svg>`;
const box = (x: number, y: number, w: number, title: string, sub: string, id = '') => `<g ${id ? `id="${id}"` : ''} class="diagram-node"><rect x="${x}" y="${y}" width="${w}" height="76" rx="8"/><text x="${x + 18}" y="${y + 30}" class="node-title">${title}</text><text x="${x + 18}" y="${y + 54}" class="node-sub">${sub}</text></g>`;
const line = (d: string, height = 300, cls = '') => `<path d="${d}" class="diagram-line ${cls}" marker-end="url(#arrow-${height})"/>`;
const label = (x: number, y: number, text: string) => `<text x="${x}" y="${y}" class="edge-label">${text}</text>`;

export const slides: Slide[] = [
  {
    title: 'Equipment checkout, as a stateful system.', section: 'System overview', layout: 'technical-intro',
    html: `${eyebrow('TRAKR / TECHNICAL OVERVIEW')}<h1>Equipment checkout,<br><span class="muted">as a stateful system.</span></h1><p class="lead">Connect the physical item, borrower, condition and return.</p><div class="intro-lifecycle"><span>Identify</span><b>→</b><span>Claim</span><b>→</b><span>Return</span><small>Issue resolution runs separately.</small></div><div class="stack-line"><span>SwiftUI + Core NFC</span><span>Compose + NDEF</span><span>Firebase Auth + Firestore</span><span>Cloudflare ops</span></div>${foot('6 technical slides · ~3½ minutes · then a 3-minute native-app demo')}`,
    timing: '0:00–0:20 · 20 seconds',
    script: 'Trakr records equipment handovers in a school. A student scans an enrolled item, records its condition and creates a claim. A teacher confirms the return. The engineering problem is to keep identity, authorization and state changes consistent across native clients. We will focus on the data path, failure handling and the cost of each write batch.',
    source: 'README.md; Trakr/Models/Domain.swift; dashboard/README.md',
  },
  {
    title: 'Two paths into the same datastore.', section: 'Architecture',
    html: `${eyebrow('ARCHITECTURE / TRUST BOUNDARIES')}<h2>Two paths.<span class="muted"> One datastore.</span></h2><p class="diagram-intro">Mobile access is checked by rules. Privileged ops access is checked by the Worker.</p>${svg('Mobile: NFC tag to native client to Firestore Security Rules to Firestore. Google Authentication supplies client identity. Staff browser to authenticated Cloudflare Worker to Firestore using a service account.', `${label(22,18,'MOBILE PATH')}${box(20,42,170,'NFC tag','tr: identifier')}${box(247,42,218,'Native clients','SwiftUI / Compose')}${box(525,42,240,'Security Rules','Role + ownership + state')}${box(872,120,228,'Firestore','Equipment / claims / issues')}${line('M190 80H247')}${line('M465 80H525')}${line('M765 80H824V143H872')}${label(252,142,'↑ Firebase Auth: verified school email')}${label(22,190,'OPERATIONS PATH')}${box(20,207,200,'Staff browser','Google sign-in')}${box(350,207,300,'Cloudflare Worker','Session + authorization + audit')}${line('M220 245H350')}${line('M650 245H824V173H872')}${label(680,229,'Service account')}`, 300)}${foot('The Worker’s privileged path does not rely on mobile Security Rules. Server-held credentials stay out of the browser.')}`,
    timing: '0:20–0:55 · 35 seconds',
    script: 'The NFC tag contains an item identifier, not borrower information. The native client resolves it to equipment. Firebase Authentication supplies the verified school identity, and Security Rules enforce the mobile data boundary. Clients write directly to Firestore; no Cloud Function is required for this path. Staff operations use a separate Cloudflare Worker. That Worker validates the staff session and authorizes operations before using a server-held service account. This is a separate trust boundary: privileged access needs its own validation and audit trail.',
    source: 'Trakr/NFC/NFCService.swift; Trakr/Services/FirebaseGateway.swift; firebase/firestore.rules; dashboard/src/worker/auth.ts; dashboard/src/worker/ops.ts',
  },
  {
    title: 'Checkout has explicit failure paths.', section: 'Checkout flowchart',
    html: `${eyebrow('CONTROL FLOW / STUDENT CHECKOUT')}<h2>Confirm only <span class="muted">after commit.</span></h2><div class="flow-toolbar"><p class="diagram-intro">Validation happens locally and again at the database boundary.</p><button class="text-button" id="play-flow">Trace success path ↗</button></div>${svg('Scan and resolve item, then stage items and condition. If offline, keep staged items and retry. If online, submit atomic batch. If denied or failed, no confirmed checkout; reconcile before retry. If accepted, show receipt.', `${box(20,28,220,'Scan + resolve','Active enrolled tags only','trace-scan')}${box(300,28,230,'Stage + condition','Dedupe; record condition','trace-stage')}${line('M240 66H300',320)}<g class="diagram-node decision" id="trace-network"><path d="M672 17L752 66L672 115L592 66Z"/><text x="672" y="71" text-anchor="middle" class="node-title">Online?</text></g>${line('M530 66H592',320)}${line('M752 66H854',320)}${label(790,48,'yes')}${box(854,28,244,'Submit atomic batch','Rules validate related records','trace-commit')}${line('M672 115V140H275V206H300',320)}${label(690,135,'no')}${box(300,168,230,'Keep staged items','Reconnect before confirming')}${line('M976 104V168',320)}${label(991,143,'accept')}${box(854,168,244,'Show receipt','Checkout is now confirmed','trace-receipt')}${line('M1098 66H1110V297H746V246',320)}${label(852,284,'deny / failure')}${box(572,168,226,'No confirmation','Reconcile state before retry')}`,320)}<p class="trace-caption mono" id="trace-status" aria-live="polite">READY / trace the accepted path</p>${foot('Atomicity applies to this batch. It does not provide exclusive reservations or solve return/checkout concurrency.')}`,
    timing: '0:55–1:40 · 45 seconds',
    script: 'A scan first resolves an active enrolled tag to equipment. The staging list lets the student remove duplicates and capture issue text before confirmation. If the device is offline, the app keeps the staged list and blocks confirmation. Online, the client submits a checkout batch, claims and optional issues together. Security Rules recheck identity, schemas, equipment status and related records. The UI shows a receipt after a successful commit. A denial leaves no accepted batch; an uncertain network outcome needs reconciliation before retry. Atomicity means all these writes succeed together. It does not mean equipment has an exclusive reservation lock.',
    source: 'Trakr/Features/Checkout/CheckoutView.swift; Trakr/Services/TrakrStore.swift; Trakr/Services/FirebaseGateway.swift:276–330; firebase/firestore.rules:334–414',
  },
  {
    title: 'Equipment identity survives tag replacement.', section: 'Data model',
    html: `${eyebrow('DATA MODEL / RELATIONSHIPS + STATE')}<h2>Stable equipment.<span class="muted"> Replaceable tags.</span></h2><p class="diagram-intro">Arrows below show stored references, not enforced foreign keys.</p>${svg('A tag references equipment. A claim references equipment, student identity, checkout batch, tag at checkout and optionally a return batch. An issue references a claim. Equipment can have many claims; multiple active claims are allowed.', `${box(20,32,215,'tags','equipmentId / status')}${box(20,154,215,'checkoutBatches','studentUid / itemCount')}${box(398,86,300,'claims','equipmentId / studentUid')}${box(890,12,215,'equipment','Stable ID / serial / tagID')}${box(890,116,215,'returnBatches','teacherUid / claimCount')}${box(890,220,215,'issues','claimId / text / status')}${line('M235 70H290V9H985V12',310)}${line('M398 123H298V192H235',310)}${label(299,175,'batch ID')}${line('M698 105H787V50H890',310)}${label(746,35,'equipment ID')}${line('M698 135H890',310)}${label(740,122,'return ID?')}${line('M890 258H771V156H698',310)}${label(785,243,'claim ID')}${label(398,208,'Claim also stores tagIdAtCheckout')}${label(398,238,'and the original checkout timestamp.')}`,310)}<div class="state-strips"><p><span class="mono quiet">CLAIM</span> active <b>→</b> returned</p><p><span class="mono quiet">ISSUE WORKFLOW</span> open <b>→</b> acknowledged <b>→</b> resolved</p></div>${foot('Multiple active claims per item are allowed. A return closes the loaded active claims; issue resolution is independent.')}`,
    timing: '1:40–2:15 · 35 seconds',
    script: 'Equipment is the durable identity; a tag is replaceable. Claims reference equipment and retain the tag used at checkout, so historical records survive a tag swap. A checkout batch groups claims. A return batch records the teacher and groups claim closures. Issues reference claims and equipment and have a separate resolution workflow. These are Firestore document references represented by IDs, not relational foreign keys. Multiple active claims per item are currently allowed. The issue arrows show the intended UI workflow; the rules permit a teacher to set any of the valid issue states, rather than enforcing a strictly forward-only state machine.',
    source: 'Trakr/Models/Domain.swift; Trakr/Services/FirebaseGateway.swift; firebase/firestore.rules:181–239, 382–414',
  },
  {
    title: 'Write volume scales with items and issues.', section: 'Write-volume model',
    html: `${eyebrow('DATA VISUALIZATION / DERIVED FROM THE CLIENT CODE')}<h2>What does a checkout <span class="muted">write?</span></h2><div class="chart-layout"><div class="write-chart"><p class="chart-heading">Document writes per checkout batch</p><div class="chart-legend"><span><i class="swatch base"></i>No issues: 1 + n</span><span><i class="swatch issue"></i>Every item has an issue: 1 + 2n</span></div><div class="chart-axis"><span style="left:0">0</span><span style="left:24.39%">10</span><span style="left:48.78%">20</span><span style="left:73.17%">30</span><span style="left:100%">41</span></div>${[1,5,10,20].map(n=>`<div class="bar-group"><span class="bar-label">${n} item${n===1?'':'s'}</span><div class="bar-pair"><div class="chart-bar base" style="--bar:${(n+1)/41*100}%"><span>${n+1}</span></div><div class="chart-bar issue" style="--bar:${(2*n+1)/41*100}%"><span>${2*n+1}</span></div></div></div>`).join('')}<p class="chart-note">Counts are derived, not measured latency, billing or throughput.</p></div><div class="write-calculator"><span class="mono quiet">EXPLORE ONE CHECKOUT</span><p class="write-equation">1 + n + k</p><label for="item-count">Items <output id="items-value">5</output></label><input id="item-count" type="range" min="1" max="20" value="5"><label for="issue-count">Items with an issue <output id="issues-value">2</output></label><input id="issue-count" type="range" min="0" max="5" value="2"><p class="write-total"><output id="write-total" aria-live="polite">8</output><span>document writes</span></p><p id="write-breakdown" class="quiet small">1 batch + 5 claims + 2 issues</p></div></div>${foot('Client limit: 20 items. Return: 1 batch + c claim updates. Read/rule checks excluded; large batches still need authorization-limit validation.')}`,
    timing: '2:15–2:55 · 40 seconds',
    script: 'This chart is a deterministic count of writes constructed by the iOS gateway, not production telemetry. A checkout creates one batch document, one claim per item, and one issue document per affected item. So the total is one plus n plus k. Five items with two issues produce eight writes. The chart compares no issues against an issue on every item. Move either slider to explore the formula. The client accepts up to twenty items, but the arithmetic alone does not prove every batch is admissible under rule-evaluation limits. Reads, authentication, retries and operational audit writes are outside this count. A return writes one batch and updates c loaded claims.',
    source: 'Trakr/Services/FirebaseGateway.swift:276–352; firebase/firestore.rules:171–179',
  },
  {
    title: 'The next work is validation, not more screens.', section: 'Tradeoffs & verification',
    html: `${eyebrow('TECHNICAL EVALUATION')}<h2>What is implemented.<br><span class="muted">What still needs proof.</span></h2><div class="verification-table"><div class="verification-row table-head"><span>DECISION</span><span>IMPLEMENTED</span><span>VALIDATE NEXT</span></div><div class="verification-row"><strong>Direct client writes</strong><span>Atomic batches + rules</span><span>Worst-case rule checks and uncertain retries</span></div><div class="verification-row"><strong>Native NFC</strong><span>NDEF read / write + tag replacement</span><span>Physical tags, device matrix and school OAuth</span></div><div class="verification-row"><strong>Shared equipment</strong><span>Multiple claims + teacher return</span><span>Concurrent checkout / return and reconciliation</span></div><div class="verification-row"><strong>Lean backend</strong><span>In-app overdue calculation</span><span>Background alerts and multi-school isolation</span></div></div>${foot('Repository tests cover store, UI and rules behaviour. This presentation does not claim a fresh application test pass.')}`,
    timing: '2:55–3:30 · 35 seconds',
    script: 'The implementation deliberately keeps the backend small: direct atomic writes, database authorization and in-app overdue calculation. Those choices leave specific validation work. Test worst-case rule evaluation and interrupted requests, exercise real NFC hardware and approved school sign-in, and probe simultaneous checkout and return. Multiple claims make this an accountability system, not an exclusive booking system. Background alerts and tenant isolation would be future work. Repository tests exist, but hardware and school-environment evidence still need to be collected. In the demo, watch the records and state transitions rather than just the screens.',
    source: 'docs/mvp-verification.md; docs/production-integration.md; TrakrTests; firebase/functions/test',
  },
  {
    title: 'Watch the state change.', section: 'Native-app demo', layout: 'technical-demo',
    html: `${eyebrow('THREE-MINUTE DEMO')}<h2>Watch the <span class="muted">state change.</span></h2><div class="demo-layout"><div class="demo-sequence"><div class="detail-row"><h3>Checkout</h3><p>Scan two items, report one issue, confirm.<br><code>1 batch + 2 claims + 1 issue = 4 writes</code></p></div><div class="detail-row"><h3>Return</h3><p>Teacher reviews and closes the loaded claims.<br><code>active → returned</code></p></div><div class="detail-row"><h3>Issue</h3><p>Show the separate issue record.<br><code>open → acknowledged</code></p></div></div><div class="demo-clock"><span class="mono quiet">DEMO TIMER</span><output id="timer">3:00</output><button id="timer-toggle" class="primary">Start timer</button><button id="timer-reset" class="text-button">Reset</button></div></div>${foot('Use a prepared native-app session. Local simulation proves the UI flow, not physical NFC or cross-device synchronization.')}`,
    timing: '3:30–6:30 · 3-minute demo',
    script: '0:00–0:20: Show the prepared student account and two test items. 0:20–1:00: Scan both tags and inspect the staged list. 1:00–1:35: Mark a loose strap on one item, acknowledge the other condition, confirm and show the receipt. Explain that this gateway call creates four documents. 1:35–2:20: Switch to the teacher session, inspect active claimants and confirm return. 2:20–2:45: Show returned history and acknowledge the issue, explaining that returned does not mean repaired. 2:45–3:00: Close with the remaining validation work. Use a dedicated test environment, and explicitly identify any local simulation or fallback recording.',
    source: 'Trakr/Services/FirebaseGateway.swift:276–352; docs/presentation/demo-runbook.md',
  },
  {
    title: 'Authorization is operation-specific.', section: 'Access-control matrix', appendix: true,
    html: `${eyebrow('Q&A / SCHOOL ACCOUNTS')}<h2>Authorization is <span class="muted">operation-specific.</span></h2><div class="access-table" role="table" aria-label="School account access matrix"><div class="access-row table-head" role="row"><span role="columnheader">OPERATION</span><span role="columnheader">STUDENT</span><span role="columnheader">TEACHER</span><span role="columnheader">ENFORCEMENT</span></div>${[['Read claims / issues','Own only','School-wide','Firestore Rules'],['Create checkout','Own identity','No student checkout','Rules + batch references'],['Confirm return','Denied','Allowed','Rules + return batch'],['Manage inventory','Denied','Allowed','Rules / ops authorization'],['Web ops mutations','Denied','Staff session','Worker checks + audit']].map(r=>`<div class="access-row" role="row">${r.map(v=>`<span role="cell">${v}</span>`).join('')}</div>`).join('')}</div>${foot('Demo rules are intentionally looser. This matrix describes normal school accounts in the current single-school configuration.')}`,
    timing: 'Q&A only',
    script: 'The normal mobile path derives student or teacher roles from verified school email claims. Students can read their own claims and issues and create checkouts tied to their identity. Teachers can review records, manage inventory and confirm returns. Operations through the Worker require a staff session and separate server-side authorization. Demo accounts have intentionally relaxed rules and are not represented in this matrix. Before broader use, separate demo data and validate the deployed rule configuration. Multi-school access requires tenant isolation rather than only adding email domains.',
    source: 'firebase/firestore.rules:22–90, 241–442; dashboard/src/worker/auth.ts; dashboard/src/worker/ops.ts',
  },
];
